listener 1883
allow_anonymous true

listener 8883
cafile c:/Users/pc/Downloads/evm_project final/evm_project final/evm_project2/tls_certs/server.crt
certfile c:/Users/pc/Downloads/evm_project final/evm_project final/evm_project2/tls_certs/server.crt
keyfile c:/Users/pc/Downloads/evm_project final/evm_project final/evm_project2/tls_certs/server.key
require_certificate false
